# SPDX-FileCopyrightText: 2026 GitHub Inc.
# SPDX-License-Identifier: CC0-1.0

name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with=dev
      - name: Analysing the application code with pylint
        run: |
          poetry run pylint $(git ls-files 'src/*.py' 'src/**/*.py')

      - name: Analysing the test code with pylint
        run: |
          poetry run pylint --disable redefined-outer-name,unused-argument,pointless-statement,missing-module-docstring $(git ls-files 'tests/*.py' 'tests/**/*.py')
